spring.application.name=LojaCarro

# O nome do banco ajustado para o seu nome, conforme a orientação
spring.datasource.url=jdbc:mysql://localhost:3306/joaoguilherme?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Fortaleza
spring.datasource.username=root
# A senha ajustada para 'root', conforme a orientação
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true